apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
  namespace: consul
spec:
  meshGateway:
    mode: 'local'
  config:
    envoy_prometheus_bind_addr: '0.0.0.0:20200'

