apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: backend
  namespace: objs-fed
spec:
  failover:
    "*":  # Applies to all subsets
      datacenters: ["dc3"]  # Failover target
