apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: backend
  namespace: objs-fed
spec:
  connectTimeout: 15s
  failover:
    '*':
      targets:
      - datacenter: "dc3"

