apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: subsets
  namespace: objs-fed
spec:
  defaultSubset: v1
  subsets:
    v1:
      filter: 'Service.Meta.version == dc1'
    v3:
      filter: 'Service.Meta.version == dc3'

