apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: observability
  annotations:
    consul.hashicorp.com/service-sync: "true"
spec:
  selector: { app: jaeger-collector }
  ports:
  - name: zipkin
    port: 9411
    targetPort: 9411
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: jaeger-collector
  namespace: observability
spec:
  protocol: http

